# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK 7.x'
  inputs:
    version: 7.x

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    arguments: '--no-build'

- task: DotNetCoreCLI@2
  displayName: 'publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ADO.Api.csproj'
    zipAfterPublish: false
    modifyOutputPath: false
    arguments: '--no-build'